{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Research Value Detection",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/pilot/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv", 

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "https://docs.google.com/document/d/11qK5gJuLdMg1C_hXE0hI7LE-2hqZdwQ1WEAYJbslAu4/edit?usp=sharing",

    "data_files": [
       "data_files/abstract-NLP-HCI-Theory-Education-20.json",
      #  "data_files/prestudy/prestudy_data.csv" #set the prestudy data file
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        "context_key": "context"
    },

  #list_as_text is used when the input text is actually a list of texts, usually used for best-worst-scaling
    "list_as_text": {
      "text_list_prefix_type": 'None',
      "horizontal": True,
    },

    "user_config": {

      "allow_all_users": True,
      
      "users": [  ],
    },

    #defining the ways annotators entering the annotation system
    "login": {
      "type": 'url_direct',    #can be 'password' or 'url_direct'
      "url_argument": 'PROLIFIC_PID' # when the login type is set to 'url_direct', 'url_argument' must be setup for a direct url argument login
    },

    #password requirement will be removed if this is added, the associated function is still under development
    "require_no_password": True,

    #the jumping-to-id function will be disabled if "jumping_to_id_disabled" is True
    "jumping_to_id_disabled": False,

  #the navigation bar will be hidden to the annotators if "hide_navbar" is True
    "hide_navbar": True,

  # define the surveyflow of the system, set up the pages before and after the data annotation page
    "surveyflow": {
      "on": True,
      "order" : ['pre_annotation', 'post_annotation'],
      "pre_annotation": ['surveyflow/guideline.jsonl'],
      # "prestudy_passed": ['surveyflow/prestudy_pass.jsonl'],
      # "prestudy_failed": ['surveyflow/prestudy_fail.jsonl'],
      "post_annotation": ['surveyflow/experience.jsonl', 'surveyflow/end.jsonl'],
      # If set, we will automatically generate testing questions similar to the annotation instances, but explicitly ask the annotator to choose one option
      # "testing": ['surveyflow/testing.jsonl'],
    },

    # "prestudy": {
    #     "on": True,
    #     "minimum_score": 0.8,
    #     "groundtruth_key": 'whether_match',
    #     "question_key": 'Whether the presented sentences are discussing the same scientific finding',
    #     "answer_mapping": {'Yes': True, 'No': False},
    #     "pass_page": 'surveyflow/prestudy_pass.jsonl',
    #     "fail_page": 'surveyflow/prestudy_fail.jsonl'
    # },


    # "automatic_assignment": {
    #   #whether do automatic task assignment for annotators, default False.
    #   "on": True,
    #   "output_filename": 'task_assignment.json',
    #   "sampling_strategy:": 'random',
    #   "labels_per_instance": 5,
    #   "instance_per_annotator": 5,
    #   "test_question_per_annotator": 0, # you must set up the test question in surveyflow to use this function

    #   "users": [  ],
    # },


    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,
    "horizontal_key_bindings": true,


    "annotation_schemes": [
        {
          "annotation_type": "highlight",
          "name": "values",
          "description": "Remainder: Research values are the explicit expressions of why something is desirable or undesirable. <br> <br>Highlight all the research values in the above text",
          "labels": [
            "Research Values",
            # "Performance and Efficiency", "Methodology Development", "Theoretical Foundations",
            # "Understanding Phenomena and Mechanisms", "Practicality and Real-world Usability",
            # "Ethical and Social Considerations", "Human-centered Design and Interaction",
            # "Collaboration and Reproducibility"
          ],

          # adding requirements
          "label_requirement": {"required":False},

          # If true, numbers [1-len(labels)] will be bound to each
          # label. Highlight selection annotations with more than 10 are not supported
          # with this simple keybinding and will need to use the full item
          # specification to bind all labels to keys.
          "sequential_key_binding": False,
        },
        # {
        #     "annotation_type": "text",
        #     "name": "textbox_input",
        #     "description": "Write a list of keywords that summarize the categories of research values that you highlighted. Put down 'N/A' if none.",

        #     # adding requirements
        #     "label_requirement": {"required":True},

        #     # if you want to use multi-line textbox, turn on the text area and set the desired rows and cols of the textbox
        #     "textarea": {
        #       "on": True,
        #       "rows": 10,
        #       "cols": 70
        #     }
        # },       
    ],

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    #"html_layout": "templates/examples/fixed_keybinding_layout.html",
    "html_layout": "default",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include:
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    # if you want to use your own template,
    # please replace the string as a path to the template
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default"

}
